
package ph.maxramos.metro.soap.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AsymmetricCalculator", targetNamespace = "http://calculator.soap.metro.maxramos.ph/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AsymmetricCalculator {


    /**
     * 
     * @param addend1
     * @param addend2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://calculator.soap.metro.maxramos.ph/", className = "ph.maxramos.metro.soap.calculator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://calculator.soap.metro.maxramos.ph/", className = "ph.maxramos.metro.soap.calculator.AddResponse")
    @Action(input = "http://calculator.soap.metro.maxramos.ph/AsymmetricCalculator/addRequest", output = "http://calculator.soap.metro.maxramos.ph/AsymmetricCalculator/addResponse")
    public int add(
        @WebParam(name = "addend1", targetNamespace = "")
        int addend1,
        @WebParam(name = "addend2", targetNamespace = "")
        int addend2);

}
