
package ph.maxramos.metro.soap.calculator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SymmetricCalculatorService", targetNamespace = "http://calculator.soap.metro.maxramos.ph/", wsdlLocation = "http://localhost:8080/metro-soap-calculator/SymmetricCalculator?wsdl")
public class SymmetricCalculatorService
    extends Service
{

    private final static URL SYMMETRICCALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SYMMETRICCALCULATORSERVICE_EXCEPTION;
    private final static QName SYMMETRICCALCULATORSERVICE_QNAME = new QName("http://calculator.soap.metro.maxramos.ph/", "SymmetricCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/metro-soap-calculator/SymmetricCalculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYMMETRICCALCULATORSERVICE_WSDL_LOCATION = url;
        SYMMETRICCALCULATORSERVICE_EXCEPTION = e;
    }

    public SymmetricCalculatorService() {
        super(__getWsdlLocation(), SYMMETRICCALCULATORSERVICE_QNAME);
    }

    public SymmetricCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYMMETRICCALCULATORSERVICE_QNAME, features);
    }

    public SymmetricCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, SYMMETRICCALCULATORSERVICE_QNAME);
    }

    public SymmetricCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYMMETRICCALCULATORSERVICE_QNAME, features);
    }

    public SymmetricCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SymmetricCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SymmetricCalculator
     */
    @WebEndpoint(name = "SymmetricCalculatorPort")
    public SymmetricCalculator getSymmetricCalculatorPort() {
        return super.getPort(new QName("http://calculator.soap.metro.maxramos.ph/", "SymmetricCalculatorPort"), SymmetricCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SymmetricCalculator
     */
    @WebEndpoint(name = "SymmetricCalculatorPort")
    public SymmetricCalculator getSymmetricCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calculator.soap.metro.maxramos.ph/", "SymmetricCalculatorPort"), SymmetricCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYMMETRICCALCULATORSERVICE_EXCEPTION!= null) {
            throw SYMMETRICCALCULATORSERVICE_EXCEPTION;
        }
        return SYMMETRICCALCULATORSERVICE_WSDL_LOCATION;
    }

}
